version: '3.9'

services:
  app:
    image: python:3.12-alpine
    container_name: finca_app
    build:
      context: ./ # o puedes usar tu repo remoto si prefieres
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8081"

    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      # Base de datos
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # Redis (requerido para cache y rate limiting)
      REDIS_URL: ${REDIS_URL}

      # Seguridad
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_COOKIE_DOMAIN: ${JWT_COOKIE_DOMAIN}
      CORS_ORIGINS: ${CORS_ORIGINS}
      CACHE_WARMUP_ENABLED: 'false'

    # Carpeta persistente para archivos est√°ticos
    volumes:
      - /mifinca/static:/app/static

    # Redes compartidas con Redis, MySQL y Frontend
    networks:
      coolify:
        aliases:
          - finca
      redbd:
        aliases:
          - finca

networks:
  coolify:
    external: true
  redbd:
    external: true
